service:
  name: serverless-scala-js

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs12.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps

package:
  exclude:
    - ./**
  include:
    - target/scala-2.13/scalajs-bundler/main/lambda-opt-bundle.js*

functions:
  hello:
    handler: target/scala-2.13/scalajs-bundler/main/lambda-opt-bundle.handler
    events:
      - httpApi:
          method: get
          path: /hello
