service:
  name: serverless-scala-js

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

package:
  exclude:
    - ./**
  include:
    - target/scala-2.13/lambda-opt.js

functions:
  hello:
    handler: target/scala-2.13/lambda-opt.handleRequest
    events:
      - http:
          method: get
          path: hello
